// Offline directory of common Indian medicines, used when there is no internet.
// Kept deliberately simple and conservative: what it is for, plus one safety warning.
// It never gives doses; it always defers to the doctor.
import { words, levenshtein } from './text.js';

const m = (brands, generic, use, warning) => ({ brands, generic, use, warning });

export const MEDICINES = [
  m(['crocin', 'dolo', 'calpol', 'pacimol', 'paracip', 'metacin'], 'paracetamol',
    { en: 'for fever and pain', mr: 'ताप आणि दुखण्यासाठी', hi: 'बुखार और दर्द के लिए' },
    { en: 'Do not take more than the doctor says. Too much harms the liver.', mr: 'डॉक्टरांनी सांगितल्यापेक्षा जास्त घेऊ नका. जास्त घेतल्यास यकृताला धोका.', hi: 'डॉक्टर के बताए से ज़्यादा मत लीजिए. ज़्यादा लेने से लिवर को नुकसान.' }),
  m(['combiflam', 'brufen', 'ibugesic'], 'ibuprofen',
    { en: 'for pain and swelling', mr: 'दुखणे आणि सूज यासाठी', hi: 'दर्द और सूजन के लिए' },
    { en: 'Take after food. Can upset the stomach.', mr: 'जेवणानंतर घ्या. पोटाला त्रास होऊ शकतो.', hi: 'खाने के बाद लीजिए. पेट खराब हो सकता है.' }),
  m(['voveran', 'dynapar', 'diclomol'], 'diclofenac',
    { en: 'for pain and swelling', mr: 'दुखणे आणि सूज यासाठी', hi: 'दर्द और सूजन के लिए' },
    { en: 'Take after food. Ask the doctor if you have kidney or heart problems.', mr: 'जेवणानंतर घ्या. किडनी किंवा हृदयाचा त्रास असल्यास डॉक्टरांना विचारा.', hi: 'खाने के बाद लीजिए. किडनी या दिल की बीमारी हो तो डॉक्टर से पूछिए.' }),
  m(['saridon'], 'propyphenazone + paracetamol + caffeine',
    { en: 'for headache', mr: 'डोकेदुखीसाठी', hi: 'सिरदर्द के लिए' },
    { en: 'Do not take with other paracetamol tablets.', mr: 'इतर पॅरासिटामॉल गोळ्यांसोबत घेऊ नका.', hi: 'दूसरी पैरासिटामॉल की गोलियों के साथ मत लीजिए.' }),
  m(['disprin', 'ecosprin', 'aspirin'], 'aspirin',
    { en: 'for pain, or to thin the blood', mr: 'दुखण्यासाठी किंवा रक्त पातळ ठेवण्यासाठी', hi: 'दर्द के लिए या खून पतला रखने के लिए' },
    { en: 'Take after food. Tell the doctor about any bleeding.', mr: 'जेवणानंतर घ्या. रक्तस्राव झाल्यास डॉक्टरांना सांगा.', hi: 'खाने के बाद लीजिए. खून बहे तो डॉक्टर को बताइए.' }),
  m(['clopitab', 'clopilet', 'plavix'], 'clopidogrel',
    { en: 'to prevent blood clots', mr: 'रक्ताच्या गाठी होऊ नयेत म्हणून', hi: 'खून के थक्के रोकने के लिए' },
    { en: 'Do not stop on your own. Tell the doctor about any bleeding.', mr: 'स्वतःहून बंद करू नका. रक्तस्राव झाल्यास डॉक्टरांना सांगा.', hi: 'अपने आप बंद मत कीजिए. खून बहे तो डॉक्टर को बताइए.' }),
  m(['glycomet', 'glyciphage', 'metformin'], 'metformin',
    { en: 'for diabetes (sugar)', mr: 'मधुमेहासाठी (साखर)', hi: 'डायबिटीज़ (शुगर) के लिए' },
    { en: 'Take with or after food.', mr: 'जेवणासोबत किंवा जेवणानंतर घ्या.', hi: 'खाने के साथ या खाने के बाद लीजिए.' }),
  m(['amaryl', 'glimisave', 'glimepiride'], 'glimepiride',
    { en: 'for diabetes (sugar)', mr: 'मधुमेहासाठी (साखर)', hi: 'डायबिटीज़ (शुगर) के लिए' },
    { en: 'Eat on time. Sugar can drop too low; keep something sweet nearby.', mr: 'वेळेवर जेवा. साखर खूप कमी होऊ शकते; जवळ गोड पदार्थ ठेवा.', hi: 'समय पर खाना खाइए. शुगर बहुत कम हो सकती है; पास में कुछ मीठा रखिए.' }),
  m(['januvia', 'istavel', 'sitagliptin'], 'sitagliptin',
    { en: 'for diabetes (sugar)', mr: 'मधुमेहासाठी (साखर)', hi: 'डायबिटीज़ (शुगर) के लिए' },
    { en: 'Take exactly as the doctor says.', mr: 'डॉक्टरांनी सांगितल्याप्रमाणेच घ्या.', hi: 'डॉक्टर ने जैसा बताया वैसा ही लीजिए.' }),
  m(['amlong', 'amlodac', 'stamlo', 'amlodipine'], 'amlodipine',
    { en: 'for high blood pressure', mr: 'उच्च रक्तदाबासाठी', hi: 'हाई ब्लड प्रेशर के लिए' },
    { en: 'Take every day. Do not stop on your own.', mr: 'रोज घ्या. स्वतःहून बंद करू नका.', hi: 'रोज़ लीजिए. अपने आप बंद मत कीजिए.' }),
  m(['telma', 'telmikind', 'telmisartan'], 'telmisartan',
    { en: 'for high blood pressure', mr: 'उच्च रक्तदाबासाठी', hi: 'हाई ब्लड प्रेशर के लिए' },
    { en: 'Take every day. Get up slowly if you feel dizzy.', mr: 'रोज घ्या. चक्कर आल्यास हळू उठा.', hi: 'रोज़ लीजिए. चक्कर आए तो धीरे उठिए.' }),
  m(['losar', 'repace', 'losartan'], 'losartan',
    { en: 'for high blood pressure', mr: 'उच्च रक्तदाबासाठी', hi: 'हाई ब्लड प्रेशर के लिए' },
    { en: 'Take every day. Do not stop on your own.', mr: 'रोज घ्या. स्वतःहून बंद करू नका.', hi: 'रोज़ लीजिए. अपने आप बंद मत कीजिए.' }),
  m(['atorva', 'lipitor', 'atorvastatin'], 'atorvastatin',
    { en: 'for cholesterol', mr: 'कोलेस्टेरॉलसाठी', hi: 'कोलेस्ट्रॉल के लिए' },
    { en: 'Tell the doctor about any muscle pain.', mr: 'स्नायू दुखल्यास डॉक्टरांना सांगा.', hi: 'मांसपेशियों में दर्द हो तो डॉक्टर को बताइए.' }),
  m(['rosuvas', 'rozavel', 'rosuvastatin'], 'rosuvastatin',
    { en: 'for cholesterol', mr: 'कोलेस्टेरॉलसाठी', hi: 'कोलेस्ट्रॉल के लिए' },
    { en: 'Tell the doctor about any muscle pain.', mr: 'स्नायू दुखल्यास डॉक्टरांना सांगा.', hi: 'मांसपेशियों में दर्द हो तो डॉक्टर को बताइए.' }),
  m(['thyronorm', 'eltroxin', 'thyrox', 'levothyroxine'], 'levothyroxine',
    { en: 'for thyroid', mr: 'थायरॉईडसाठी', hi: 'थायराइड के लिए' },
    { en: 'Take in the morning on an empty stomach.', mr: 'सकाळी उपाशीपोटी घ्या.', hi: 'सुबह खाली पेट लीजिए.' }),
  m(['pantocid', 'pantop', 'pantoprazole'], 'pantoprazole',
    { en: 'for acidity', mr: 'ॲसिडिटीसाठी', hi: 'एसिडिटी के लिए' },
    { en: 'Take before breakfast.', mr: 'नाश्त्याआधी घ्या.', hi: 'नाश्ते से पहले लीजिए.' }),
  m(['omez', 'ocid', 'omeprazole'], 'omeprazole',
    { en: 'for acidity', mr: 'ॲसिडिटीसाठी', hi: 'एसिडिटी के लिए' },
    { en: 'Take before food.', mr: 'जेवणाआधी घ्या.', hi: 'खाने से पहले लीजिए.' }),
  m(['razo', 'rablet', 'rabeprazole'], 'rabeprazole',
    { en: 'for acidity', mr: 'ॲसिडिटीसाठी', hi: 'एसिडिटी के लिए' },
    { en: 'Take before food.', mr: 'जेवणाआधी घ्या.', hi: 'खाने से पहले लीजिए.' }),
  m(['digene', 'gelusil'], 'antacid',
    { en: 'for acidity and gas', mr: 'ॲसिडिटी आणि गॅससाठी', hi: 'एसिडिटी और गैस के लिए' },
    { en: 'Keep 2 hours apart from other medicines.', mr: 'इतर औषधांपासून 2 तासांचे अंतर ठेवा.', hi: 'दूसरी दवाइयों से 2 घंटे का अंतर रखिए.' }),
  m(['emeset', 'ondem', 'ondansetron'], 'ondansetron',
    { en: 'for vomiting', mr: 'उलटीसाठी', hi: 'उल्टी के लिए' },
    { en: 'Take exactly as the doctor says.', mr: 'डॉक्टरांनी सांगितल्याप्रमाणेच घ्या.', hi: 'डॉक्टर ने जैसा बताया वैसा ही लीजिए.' }),
  m(['domstal', 'domperidone'], 'domperidone',
    { en: 'for vomiting and gas', mr: 'उलटी आणि गॅससाठी', hi: 'उल्टी और गैस के लिए' },
    { en: 'Take before food.', mr: 'जेवणाआधी घ्या.', hi: 'खाने से पहले लीजिए.' }),
  m(['eldoper', 'imodium', 'loperamide'], 'loperamide',
    { en: 'for loose motions', mr: 'जुलाबासाठी', hi: 'दस्त के लिए' },
    { en: 'Drink ORS water. See a doctor if there is blood or fever.', mr: 'ORS पाणी प्या. रक्त किंवा ताप असल्यास डॉक्टरांकडे जा.', hi: 'ORS पानी पीजिए. खून या बुखार हो तो डॉक्टर के पास जाइए.' }),
  m(['flagyl', 'metrogyl', 'metronidazole'], 'metronidazole',
    { en: 'for stomach infection', mr: 'पोटाच्या संसर्गासाठी', hi: 'पेट के संक्रमण के लिए' },
    { en: 'No alcohol while taking this. Finish the full course.', mr: 'हे घेताना दारू पिऊ नका. पूर्ण कोर्स करा.', hi: 'यह लेते समय शराब मत पीजिए. पूरा कोर्स कीजिए.' }),
  m(['azithral', 'azee', 'zithromax', 'azithromycin'], 'azithromycin',
    { en: 'antibiotic for infection', mr: 'संसर्गासाठी अँटिबायोटिक', hi: 'संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Finish the full course, even if you feel better.', mr: 'बरे वाटले तरी पूर्ण कोर्स करा.', hi: 'ठीक लगे तब भी पूरा कोर्स कीजिए.' }),
  m(['augmentin', 'mox', 'novamox', 'amoxicillin'], 'amoxicillin',
    { en: 'antibiotic for infection', mr: 'संसर्गासाठी अँटिबायोटिक', hi: 'संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Finish the full course. Stop and call the doctor if you get a rash.', mr: 'पूर्ण कोर्स करा. पुरळ आल्यास थांबा आणि डॉक्टरांना फोन करा.', hi: 'पूरा कोर्स कीजिए. दाने निकलें तो रोकिए और डॉक्टर को फ़ोन कीजिए.' }),
  m(['ciplox', 'cifran', 'ciprofloxacin'], 'ciprofloxacin',
    { en: 'antibiotic for infection', mr: 'संसर्गासाठी अँटिबायोटिक', hi: 'संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Finish the full course. Drink plenty of water.', mr: 'पूर्ण कोर्स करा. भरपूर पाणी प्या.', hi: 'पूरा कोर्स कीजिए. खूब पानी पीजिए.' }),
  m(['cetzine', 'okacet', 'alerid', 'cetirizine'], 'cetirizine',
    { en: 'for allergy, sneezing and itching', mr: 'ॲलर्जी, शिंका आणि खाज यासाठी', hi: 'एलर्जी, छींक और खुजली के लिए' },
    { en: 'May make you sleepy. Do not drive after taking it.', mr: 'झोप येऊ शकते. घेतल्यानंतर गाडी चालवू नका.', hi: 'नींद आ सकती है. लेने के बाद गाड़ी मत चलाइए.' }),
  m(['allegra', 'fexofenadine'], 'fexofenadine',
    { en: 'for allergy', mr: 'ॲलर्जीसाठी', hi: 'एलर्जी के लिए' },
    { en: 'Do not take with fruit juice.', mr: 'फळांच्या रसासोबत घेऊ नका.', hi: 'फलों के रस के साथ मत लीजिए.' }),
  m(['montair', 'montek', 'montelukast'], 'montelukast',
    { en: 'for asthma and allergy', mr: 'दमा आणि ॲलर्जीसाठी', hi: 'दमा और एलर्जी के लिए' },
    { en: 'Usually taken at night.', mr: 'सहसा रात्री घेतात.', hi: 'आमतौर पर रात में लेते हैं.' }),
  m(['benadryl', 'ascoril', 'grilinctus', 'corex'], 'cough syrup',
    { en: 'for cough', mr: 'खोकल्यासाठी', hi: 'खांसी के लिए' },
    { en: 'May make you sleepy. Use the measuring cup.', mr: 'झोप येऊ शकते. मापाच्या कपानेच घ्या.', hi: 'नींद आ सकती है. नापने वाले कप से ही लीजिए.' }),
  m(['shelcal', 'calcimax', 'ccm'], 'calcium + vitamin D',
    { en: 'for bones (calcium)', mr: 'हाडांसाठी (कॅल्शियम)', hi: 'हड्डियों के लिए (कैल्शियम)' },
    { en: 'Take after food.', mr: 'जेवणानंतर घ्या.', hi: 'खाने के बाद लीजिए.' }),
  m(['uprise', 'calcirol', 'd3must'], 'vitamin D3',
    { en: 'vitamin D', mr: 'व्हिटॅमिन डी', hi: 'विटामिन डी' },
    { en: 'Often taken only once a week. Check the doctor’s note.', mr: 'बहुतेक वेळा आठवड्यातून एकदाच घेतात. डॉक्टरांची चिठ्ठी पाहा.', hi: 'अक्सर हफ़्ते में एक बार ही लेते हैं. डॉक्टर की पर्ची देखिए.' }),
  m(['becosules', 'zincovit', 'neurobion', 'supradyn'], 'multivitamin',
    { en: 'vitamins', mr: 'जीवनसत्त्वे (व्हिटॅमिन)', hi: 'विटामिन' },
    { en: 'Take after food.', mr: 'जेवणानंतर घ्या.', hi: 'खाने के बाद लीजिए.' }),
  m(['electral', 'ors'], 'oral rehydration salts',
    { en: 'for weakness from loose motions or heat', mr: 'जुलाब किंवा उन्हामुळे आलेल्या अशक्तपणासाठी', hi: 'दस्त या गर्मी से आई कमज़ोरी के लिए' },
    { en: 'Mix in clean water exactly as written on the packet.', mr: 'पाकिटावर लिहिल्याप्रमाणे स्वच्छ पाण्यात मिसळा.', hi: 'पैकेट पर लिखे अनुसार साफ़ पानी में मिलाइए.' }),
  m(['levocet', 'xyzal', 'levocetirizine'], 'levocetirizine',
    { en: 'for allergy, sneezing and itching', mr: 'ॲलर्जी, शिंका आणि खाज यासाठी', hi: 'एलर्जी, छींक और खुजली के लिए' },
    { en: 'May make you sleepy. Do not drive after taking it.', mr: 'झोप येऊ शकते. घेतल्यानंतर गाडी चालवू नका.', hi: 'नींद आ सकती है. लेने के बाद गाड़ी मत चलाइए.' }),
  m(['taxim', 'zifi', 'cefixime'], 'cefixime',
    { en: 'antibiotic for infection', mr: 'संसर्गासाठी अँटिबायोटिक', hi: 'संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Finish the full course, even if you feel better.', mr: 'बरे वाटले तरी पूर्ण कोर्स करा.', hi: 'ठीक लगे तब भी पूरा कोर्स कीजिए.' }),
  m(['doxy', 'doxt', 'doxycycline'], 'doxycycline',
    { en: 'antibiotic for infection', mr: 'संसर्गासाठी अँटिबायोटिक', hi: 'संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Take with a full glass of water. Do not lie down right after.', mr: 'पूर्ण ग्लास पाण्यासोबत घ्या. लगेच झोपू नका.', hi: 'पूरे गिलास पानी के साथ लीजिए. तुरंत लेटिए मत.' }),
  m(['norflox', 'norfloxacin'], 'norfloxacin',
    { en: 'antibiotic for urine or stomach infection', mr: 'लघवी किंवा पोटाच्या संसर्गासाठी अँटिबायोटिक', hi: 'पेशाब या पेट के संक्रमण के लिए एंटीबायोटिक' },
    { en: 'Finish the full course. Drink plenty of water.', mr: 'पूर्ण कोर्स करा. भरपूर पाणी प्या.', hi: 'पूरा कोर्स कीजिए. खूब पानी पीजिए.' }),
  m(['wysolone', 'omnacortil', 'prednisolone'], 'prednisolone',
    { en: 'steroid for swelling, asthma or allergy', mr: 'सूज, दमा किंवा ॲलर्जीसाठी स्टिरॉइड', hi: 'सूजन, दमा या एलर्जी के लिए स्टेरॉयड' },
    { en: 'Do not stop suddenly. Take after food. Can raise sugar.', mr: 'अचानक बंद करू नका. जेवणानंतर घ्या. साखर वाढू शकते.', hi: 'अचानक बंद मत कीजिए. खाने के बाद लीजिए. शुगर बढ़ सकती है.' }),
  m(['mixtard', 'lantus', 'huminsulin', 'insulin'], 'insulin',
    { en: 'for diabetes (sugar), injection', mr: 'मधुमेहासाठी (साखर) इंजेक्शन', hi: 'डायबिटीज़ (शुगर) के लिए इंजेक्शन' },
    { en: 'Keep in the fridge, not the freezer. Eat on time; sugar can drop too low.', mr: 'फ्रिजमध्ये ठेवा, फ्रीजरमध्ये नाही. वेळेवर जेवा; साखर खूप कमी होऊ शकते.', hi: 'फ्रिज में रखिए, फ्रीज़र में नहीं. समय पर खाना खाइए; शुगर बहुत कम हो सकती है.' }),
  m(['sorbitrate', 'isordil'], 'isosorbide dinitrate',
    { en: 'for chest pain (heart)', mr: 'छातीतील दुखण्यासाठी (हृदय)', hi: 'सीने के दर्द के लिए (दिल)' },
    { en: 'If chest pain does not stop in 5 minutes, call 108 at once.', mr: '5 मिनिटांत छातीतील दुखणे थांबले नाही तर लगेच 108 ला फोन करा.', hi: '5 मिनट में सीने का दर्द न रुके तो तुरंत 108 पर फ़ोन कीजिए.' }),
  m(['aten', 'tenormin', 'atenolol'], 'atenolol',
    { en: 'for blood pressure and heart', mr: 'रक्तदाब आणि हृदयासाठी', hi: 'ब्लड प्रेशर और दिल के लिए' },
    { en: 'Do not stop suddenly.', mr: 'अचानक बंद करू नका.', hi: 'अचानक बंद मत कीजिए.' }),
  m(['metolar', 'metxl', 'starpress', 'metoprolol'], 'metoprolol',
    { en: 'for blood pressure and heart', mr: 'रक्तदाब आणि हृदयासाठी', hi: 'ब्लड प्रेशर और दिल के लिए' },
    { en: 'Do not stop suddenly.', mr: 'अचानक बंद करू नका.', hi: 'अचानक बंद मत कीजिए.' }),
  m(['lasix', 'furosemide'], 'furosemide',
    { en: 'water tablet, for swelling or blood pressure', mr: 'लघवी वाढवणारी गोळी, सूज किंवा रक्तदाबासाठी', hi: 'पेशाब बढ़ाने वाली गोली, सूजन या ब्लड प्रेशर के लिए' },
    { en: 'Take in the morning, not at night.', mr: 'सकाळी घ्या, रात्री नाही.', hi: 'सुबह लीजिए, रात को नहीं.' }),
  m(['warf', 'acitrom', 'warfarin'], 'blood thinner',
    { en: 'blood thinner', mr: 'रक्त पातळ करणारे औषध', hi: 'खून पतला करने की दवा' },
    { en: 'Regular blood tests needed. Tell the doctor about any bleeding.', mr: 'नियमित रक्त तपासणी लागते. रक्तस्राव झाल्यास डॉक्टरांना सांगा.', hi: 'नियमित खून की जाँच ज़रूरी है. खून बहे तो डॉक्टर को बताइए.' }),
  m(['alprax', 'restyl', 'alprazolam'], 'alprazolam',
    { en: 'for anxiety or sleep', mr: 'चिंता किंवा झोपेसाठी', hi: 'घबराहट या नींद के लिए' },
    { en: 'Makes you sleepy; risk of falling. Never take more than prescribed.', mr: 'झोप येते; पडण्याचा धोका. सांगितल्यापेक्षा जास्त कधीही घेऊ नका.', hi: 'नींद आती है; गिरने का खतरा. बताए से ज़्यादा कभी मत लीजिए.' }),
  m(['nurokind', 'methycobal', 'mecobalamin'], 'vitamin B12',
    { en: 'vitamin B12, for nerves', mr: 'व्हिटॅमिन B12, नसांसाठी', hi: 'विटामिन B12, नसों के लिए' },
    { en: 'Take after food.', mr: 'जेवणानंतर घ्या.', hi: 'खाने के बाद लीजिए.' }),
  m(['livogen', 'dexorange', 'autrin'], 'iron',
    { en: 'iron, for weakness and low blood', mr: 'लोह, अशक्तपणा आणि रक्त कमी असल्यास', hi: 'आयरन, कमज़ोरी और खून की कमी के लिए' },
    { en: 'Stool may turn black; this is normal. Do not take with tea.', mr: 'शौच काळी होऊ शकते; हे सामान्य आहे. चहासोबत घेऊ नका.', hi: 'मल काला हो सकता है; यह सामान्य है. चाय के साथ मत लीजिए.' }),
  m(['mucolite', 'ambrodil', 'ambroxol'], 'ambroxol',
    { en: 'for cough with phlegm', mr: 'कफ असलेल्या खोकल्यासाठी', hi: 'बलगम वाली खांसी के लिए' },
    { en: 'Drink warm water. See a doctor if cough lasts over 2 weeks.', mr: 'कोमट पाणी प्या. 2 आठवड्यांपेक्षा जास्त खोकला असल्यास डॉक्टरांकडे जा.', hi: 'गुनगुना पानी पीजिए. 2 हफ़्ते से ज़्यादा खांसी हो तो डॉक्टर के पास जाइए.' }),
  m(['volini', 'moov', 'iodex'], 'pain relief gel',
    { en: 'pain relief gel, for the skin only', mr: 'दुखण्यावर लावण्याचे मलम, फक्त त्वचेवर', hi: 'दर्द पर लगाने का मलहम, सिर्फ़ त्वचा पर' },
    { en: 'Do not eat. Keep away from the eyes.', mr: 'खाऊ नका. डोळ्यांपासून दूर ठेवा.', hi: 'खाइए मत. आँखों से दूर रखिए.' }),
];

// Finds the medicine whose brand or generic name best matches the OCR text.
// Allows small OCR spelling mistakes (Levenshtein distance), but short names must match exactly.
export function matchMedicine(text) {
  // Inside words OCR often reads letters as digits ("D0LO"), so also try the letter version.
  const letterize = (w) => (/[a-z]/.test(w) ? w.replace(/0/g, 'o').replace(/1/g, 'l').replace(/5/g, 's') : w);
  const tokens = [...new Set(words(text).flatMap((w) => [w, letterize(w)]))];
  let best = null;
  for (const med of MEDICINES) {
    for (const name of [...med.brands, med.generic]) {
      const key = name.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (key.length < 3) continue;
      const allowed = key.length >= 8 ? 2 : key.length >= 5 ? 1 : 0;
      for (const tok of tokens) {
        if (Math.abs(tok.length - key.length) > allowed) continue;
        const d = levenshtein(tok, key);
        if (d <= allowed && (!best || d < best.distance)) best = { medicine: med, name, distance: d };
      }
    }
  }
  return best;
}
